import type { IngestibleSourceDefinition } from "@/lib/ingestion/types";

export const swedenMexicoIngestionSources: IngestibleSourceDefinition[] = [
  {
    id: "el-universal-national",
    name: "El Universal",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://www.eluniversal.com.mx/arc/outboundfeeds/rss/?outputType=xml",
    trustTier: 2,
    categories: ["domestic_politics", "society", "security"],
    enabled: true,
    sourcePriority: 78,
    credibilityScore: 78,
    defaultDetectedCountry: "Mexiko",
    maxItemsPerRun: 25,
  },
  {
    id: "la-jornada-politica",
    name: "La Jornada Politica",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://www.jornada.com.mx/rss/politica.xml",
    trustTier: 2,
    categories: ["domestic_politics", "society", "foreign_policy"],
    enabled: true,
    sourcePriority: 74,
    credibilityScore: 76,
    defaultDetectedCountry: "Mexiko",
    maxItemsPerRun: 25,
  },
  {
    id: "el-financiero",
    name: "El Financiero",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://www.elfinanciero.com.mx/arc/outboundfeeds/rss/?outputType=xml",
    trustTier: 2,
    categories: ["economy", "markets", "trade"],
    enabled: true,
    sourcePriority: 82,
    credibilityScore: 80,
    defaultDetectedCountry: "Mexiko",
    maxItemsPerRun: 30,
  },
  {
    id: "expansion-mexico",
    name: "Expansion Mexico",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://expansion.mx/rss",
    trustTier: 2,
    categories: ["economy", "investment_climate", "technology"],
    enabled: true,
    sourcePriority: 76,
    credibilityScore: 78,
    defaultDetectedCountry: "Mexiko",
    maxItemsPerRun: 30,
  },
  {
    id: "el-sol-de-mexico",
    name: "El Sol de Mexico",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://oem.com.mx/elsoldemexico/rss",
    trustTier: 2,
    categories: ["domestic_politics", "society", "security"],
    enabled: true,
    sourcePriority: 68,
    credibilityScore: 72,
    defaultDetectedCountry: "Mexiko",
    maxItemsPerRun: 25,
  },
  {
    id: "diario-de-yucatan",
    name: "Diario de Yucatan",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://www.yucatan.com.mx/feed",
    trustTier: 2,
    categories: ["society", "security", "culture_soft_power"],
    enabled: true,
    sourcePriority: 68,
    credibilityScore: 75,
    defaultDetectedCountry: "Mexiko",
    defaultDetectedRegion: "yucatan",
    regionalScope: ["yucatan", "quintana-roo", "campeche"],
    maxItemsPerRun: 25,
  },
  {
    id: "am-guanajuato",
    name: "AM Guanajuato",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://www.am.com.mx/feed",
    trustTier: 2,
    categories: ["security", "society", "investment_climate"],
    enabled: true,
    sourcePriority: 73,
    credibilityScore: 74,
    defaultDetectedCountry: "Mexiko",
    defaultDetectedRegion: "guanajuato",
    regionalScope: ["guanajuato"],
    maxItemsPerRun: 25,
  },
  {
    id: "el-occidental-jalisco",
    name: "El Occidental",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://oem.com.mx/eloccidental/rss",
    trustTier: 2,
    categories: ["society", "security", "technology"],
    enabled: true,
    sourcePriority: 68,
    credibilityScore: 72,
    defaultDetectedCountry: "Mexiko",
    defaultDetectedRegion: "jalisco",
    regionalScope: ["jalisco"],
    maxItemsPerRun: 25,
  },
  {
    id: "el-sol-de-tijuana",
    name: "El Sol de Tijuana",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://oem.com.mx/elsoldetijuana/rss",
    trustTier: 2,
    categories: ["migration", "security", "trade"],
    enabled: true,
    sourcePriority: 72,
    credibilityScore: 72,
    defaultDetectedCountry: "Mexiko",
    defaultDetectedRegion: "baja-california",
    regionalScope: ["baja-california"],
    maxItemsPerRun: 25,
  },
  {
    id: "el-sol-de-puebla",
    name: "El Sol de Puebla",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://oem.com.mx/elsoldepuebla/rss",
    trustTier: 2,
    categories: ["domestic_politics", "society", "security"],
    enabled: true,
    sourcePriority: 66,
    credibilityScore: 71,
    defaultDetectedCountry: "Mexiko",
    defaultDetectedRegion: "puebla",
    regionalScope: ["puebla"],
    maxItemsPerRun: 25,
  },
  {
    id: "el-sol-de-san-luis",
    name: "El Sol de San Luis",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://oem.com.mx/elsoldesanluis/rss",
    trustTier: 2,
    categories: ["investment_climate", "security", "society"],
    enabled: true,
    sourcePriority: 65,
    credibilityScore: 70,
    defaultDetectedCountry: "Mexiko",
    defaultDetectedRegion: "san-luis-potosi",
    regionalScope: ["san-luis-potosi"],
    maxItemsPerRun: 25,
  },
  {
    id: "el-economista-ultimas-noticias",
    name: "El Economista Ultimas Noticias",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://www.eleconomista.com.mx/rss/ultimas-noticias",
    trustTier: 2,
    categories: ["economy", "markets", "trade"],
    enabled: true,
    sourcePriority: 80,
    credibilityScore: 82,
    defaultDetectedCountry: "Mexiko",
    maxItemsPerRun: 30,
  },
  {
    id: "milenio-rss",
    name: "Milenio RSS",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://www.milenio.com/api/v1/rss",
    trustTier: 2,
    categories: ["domestic_politics", "security", "society"],
    enabled: true,
    sourcePriority: 78,
    credibilityScore: 78,
    defaultDetectedCountry: "Mexiko",
    maxItemsPerRun: 25,
  },
  {
    id: "aristegui-noticias-rss",
    name: "Aristegui Noticias RSS",
    country: "Mexiko",
    language: "es",
    type: "rss",
    sourceType: "news",
    url: "https://aristeguinoticias.com/?format=rss",
    trustTier: 2,
    categories: ["domestic_politics", "security", "society"],
    enabled: true,
    sourcePriority: 76,
    credibilityScore: 80,
    defaultDetectedCountry: "Mexiko",
    maxItemsPerRun: 25,
  },
  {
    id: "animal-politico-politica",
    name: "Animal Politico Politica",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "news",
    url: "https://grupoanimal.mx/politica",
    trustTier: 2,
    categories: ["domestic_politics", "security", "society"],
    enabled: true,
    sourcePriority: 78,
    credibilityScore: 84,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "animal-politico-seguridad",
    name: "Animal Politico Seguridad",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "news",
    url: "https://grupoanimal.mx/seguridad",
    trustTier: 2,
    categories: ["security", "domestic_politics", "society"],
    enabled: true,
    sourcePriority: 80,
    credibilityScore: 84,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "animal-politico-estados",
    name: "Animal Politico Estados",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "news",
    url: "https://grupoanimal.mx/estados",
    trustTier: 2,
    categories: ["domestic_politics", "society", "security"],
    enabled: true,
    sourcePriority: 76,
    credibilityScore: 84,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "presidencia-mexico",
    name: "Gobierno de Mexico Presidencia",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "government",
    url: "https://www.gob.mx/presidencia/archivo/prensa",
    trustTier: 1,
    categories: ["domestic_politics", "foreign_policy"],
    enabled: true,
    sourcePriority: 92,
    credibilityScore: 96,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "sre-mexico",
    name: "Secretaria de Relaciones Exteriores",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "government",
    url: "https://www.gob.mx/sre/archivo/prensa",
    trustTier: 1,
    categories: ["foreign_policy", "sweden_connection"],
    enabled: true,
    sourcePriority: 95,
    credibilityScore: 96,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "secretaria-economia",
    name: "Secretaria de Economia",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "government",
    url: "https://www.gob.mx/se/archivo/prensa",
    trustTier: 1,
    categories: ["economy", "trade", "investment_climate"],
    enabled: true,
    sourcePriority: 88,
    credibilityScore: 95,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "hacienda-mexico",
    name: "Secretaria de Hacienda",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "government",
    url: "https://www.gob.mx/hacienda/archivo/prensa",
    trustTier: 1,
    categories: ["economy", "markets"],
    enabled: true,
    sourcePriority: 88,
    credibilityScore: 95,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "seguridad-mexico",
    name: "Secretaria de Seguridad y Proteccion Ciudadana",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "government",
    url: "https://www.gob.mx/sspc/archivo/prensa",
    trustTier: 1,
    categories: ["security", "domestic_politics"],
    enabled: true,
    sourcePriority: 90,
    credibilityScore: 95,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "instituto-nacional-migracion",
    name: "Instituto Nacional de Migracion",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "government",
    url: "https://www.gob.mx/inm/archivo/prensa",
    trustTier: 1,
    categories: ["migration", "security"],
    enabled: true,
    sourcePriority: 90,
    credibilityScore: 95,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "banxico-press",
    name: "Banco de Mexico",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceCategory: "government",
    retrieval: { primary: "website" },
    retrievalMethod: "website",
    sourceType: "government",
    url: "https://www.banxico.org.mx/noticias/noticias001.html",
    trustTier: 1,
    categories: ["economy", "markets"],
    enabled: false,
    notes:
      "Pausad tills Banxico-hämtning kan göras utan specialcrawler. Viktiga Banxico-beslut fångas normalt via ekonomi- och marknadskällor.",
    sourcePriority: 94,
    credibilityScore: 98,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "inegi-comunicados",
    name: "INEGI Comunicados",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "institution",
    url: "https://www.inegi.org.mx/app/saladeprensa/",
    trustTier: 1,
    categories: ["economy", "society"],
    enabled: true,
    sourcePriority: 88,
    credibilityScore: 98,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "ine-mexico",
    name: "Instituto Nacional Electoral",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "institution",
    url: "https://centralelectoral.ine.mx/",
    trustTier: 1,
    categories: ["domestic_politics", "society"],
    enabled: true,
    sourcePriority: 86,
    credibilityScore: 96,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "diario-oficial-federacion",
    name: "Diario Oficial de la Federacion",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "government",
    url: "https://www.dof.gob.mx/",
    trustTier: 1,
    categories: ["domestic_politics", "economy", "trade"],
    enabled: true,
    sourcePriority: 90,
    credibilityScore: 98,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "scjn-mexico",
    name: "Suprema Corte de Justicia de la Nacion",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceType: "institution",
    url: "https://www.internet2.scjn.gob.mx/red2/comunicados/",
    trustTier: 1,
    categories: ["domestic_politics", "society"],
    enabled: true,
    sourcePriority: 86,
    credibilityScore: 96,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "sweden-abroad-mexico",
    name: "Sweden Abroad Mexico",
    country: "Sverige",
    language: "sv",
    type: "website",
    sourceType: "government",
    url: "https://www.swedenabroad.se/sv/utlandsmyndigheter/mexico-mexico-city/",
    trustTier: 1,
    categories: ["sweden_connection", "culture_soft_power", "foreign_policy"],
    enabled: true,
    sourcePriority: 96,
    credibilityScore: 98,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "sweden-abroad-mexico-reseinformation",
    name: "Sweden Abroad Mexico reseinformation",
    country: "Sverige",
    language: "sv",
    type: "website",
    sourceType: "advisory",
    url: "https://www.swedenabroad.se/sv/om-utlandet-f%C3%B6r-svenska-medborgare/mexiko/",
    trustTier: 1,
    categories: ["security", "sweden_connection", "society"],
    enabled: true,
    sourcePriority: 94,
    credibilityScore: 98,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "regeringen-utrikes",
    name: "Regeringen Utrikesdepartementet",
    country: "Sverige",
    language: "sv",
    type: "website",
    sourceType: "government",
    url: "https://www.regeringen.se/sveriges-regering/utrikesdepartementet/",
    trustTier: 1,
    categories: ["foreign_policy", "sweden_connection"],
    enabled: true,
    sourcePriority: 90,
    credibilityScore: 98,
    preserveRawContent: true,
  },
  {
    id: "business-sweden-mexico",
    name: "Business Sweden Mexico",
    country: "Sverige",
    language: "en",
    type: "website",
    sourceType: "institution",
    url: "https://www.business-sweden.com/markets/americas/mexico/",
    trustTier: 1,
    categories: ["trade", "investment_climate", "sweden_connection"],
    enabled: true,
    sourcePriority: 88,
    credibilityScore: 94,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "riksbanken-press",
    name: "Riksbanken pressmeddelanden",
    country: "Sverige",
    language: "sv",
    type: "rss",
    sourceType: "institution",
    url: "https://www.riksbank.se/sv/rss/pressmeddelanden/",
    trustTier: 1,
    categories: ["economy", "markets", "sweden_connection"],
    enabled: true,
    sourcePriority: 76,
    credibilityScore: 98,
    maxItemsPerRun: 15,
  },
  {
    id: "riksbanken-news",
    name: "Riksbanken nyheter",
    country: "Sverige",
    language: "sv",
    type: "rss",
    sourceType: "institution",
    url: "https://www.riksbank.se/sv/rss/nyheter/",
    trustTier: 1,
    categories: ["economy", "markets", "sweden_connection"],
    enabled: true,
    sourcePriority: 74,
    credibilityScore: 98,
    maxItemsPerRun: 15,
  },
  {
    id: "bbc-latin-america",
    name: "BBC Latin America",
    country: "Storbritannien",
    language: "en",
    type: "rss",
    sourceType: "news",
    url: "https://feeds.bbci.co.uk/news/world/latin_america/rss.xml",
    trustTier: 2,
    categories: ["foreign_policy", "security", "society"],
    enabled: true,
    sourcePriority: 76,
    credibilityScore: 82,
    maxItemsPerRun: 25,
  },
  {
    id: "reuters-americas",
    name: "Reuters Americas",
    country: "Internationell",
    language: "en",
    type: "website",
    sourceType: "news",
    url: "https://www.reuters.com/world/americas/",
    trustTier: 1,
    categories: ["foreign_policy", "economy", "security"],
    enabled: false,
    notes:
      "Pausad. Reuters skyddar denna sektion med anti-bot/JS-gate och ingen stabil offentlig RSS-feed kunde verifieras.",
    sourcePriority: 88,
    credibilityScore: 94,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "ap-mexico",
    name: "Associated Press Mexico",
    country: "USA",
    language: "en",
    type: "website",
    sourceType: "news",
    url: "https://apnews.com/hub/mexico",
    trustTier: 1,
    categories: ["domestic_politics", "security", "society"],
    enabled: true,
    sourcePriority: 84,
    credibilityScore: 93,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "financial-times-mexico",
    name: "Financial Times Mexico",
    country: "Storbritannien",
    language: "en",
    type: "website",
    sourceType: "news",
    url: "https://www.ft.com/mexico",
    trustTier: 1,
    categories: ["economy", "markets", "investment_climate"],
    enabled: true,
    notes:
      "Hämtas via FT:s publika news sitemap som metadata-signal. Används som kompletterande indikator, inte som fullständig textkälla.",
    sourcePriority: 68,
    credibilityScore: 92,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "bloomberg-mexico-markets",
    name: "Bloomberg Mexico Markets",
    country: "USA",
    language: "en",
    type: "website",
    sourceType: "other",
    url: "https://www.bloomberg.com/quote/USDMXN:CUR",
    trustTier: 1,
    categories: ["markets", "economy"],
    enabled: true,
    sourceCategory: "market",
    retrieval: { primary: "website" },
    notes:
      "Marknadskälla för USD/MXN. Skapar bara signaler när valutakursen avviker tydligt, inte vid vardagligt marknadsbrus.",
    sourcePriority: 78,
    credibilityScore: 90,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "eeas-mexico",
    name: "EU External Action Service Mexico",
    country: "EU",
    language: "en",
    type: "website",
    sourceType: "institution",
    url: "https://www.eeas.europa.eu/delegations/mexico_en",
    trustTier: 1,
    categories: ["foreign_policy", "trade", "sweden_connection"],
    enabled: true,
    sourcePriority: 86,
    credibilityScore: 97,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "un-mexico",
    name: "United Nations Mexico",
    country: "Internationell",
    language: "es",
    type: "website",
    sourceType: "institution",
    url: "https://mexico.un.org/es",
    trustTier: 1,
    categories: ["society", "migration", "foreign_policy"],
    enabled: true,
    sourcePriority: 82,
    credibilityScore: 97,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "imf-mexico",
    name: "IMF Mexico",
    country: "Internationell",
    language: "en",
    type: "website",
    sourceType: "institution",
    url: "https://www.imf.org/en/Countries/MEX",
    trustTier: 1,
    categories: ["economy", "markets"],
    enabled: true,
    sourcePriority: 86,
    credibilityScore: 98,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "oecd-mexico",
    name: "OECD Mexico",
    country: "Internationell",
    language: "en",
    type: "website",
    sourceType: "institution",
    url: "https://www.oecd.org/mexico/",
    websiteUrl: "https://www.oecd.org/en/countries/mexico.html",
    trustTier: 1,
    categories: ["economy", "trade", "society"],
    enabled: true,
    sourcePriority: 84,
    credibilityScore: 98,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "world-bank-mexico",
    name: "World Bank Mexico",
    country: "Internationell",
    language: "en",
    type: "website",
    sourceType: "institution",
    url: "https://www.worldbank.org/en/country/mexico",
    trustTier: 1,
    categories: ["economy", "investment_climate", "society"],
    enabled: true,
    sourcePriority: 84,
    credibilityScore: 98,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "oas-mexico",
    name: "Organization of American States",
    country: "Internationell",
    language: "en",
    type: "website",
    sourceType: "institution",
    url: "https://www.oas.org/en/member_states/member_state.asp?sCode=MEX",
    trustTier: 1,
    categories: ["foreign_policy", "society"],
    enabled: false,
    notes:
      "Pausad tills vidare. OAS har relevant innehåll, men nuvarande OAS-ytor svarar instabilt bakom skydd och är inte värda en specialadapter just nu.",
    sourcePriority: 74,
    credibilityScore: 96,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "us-state-mexico",
    name: "US State Department Mexico",
    country: "USA",
    language: "en",
    type: "website",
    sourceType: "government",
    url: "https://www.state.gov/countries-areas/mexico/",
    trustTier: 1,
    categories: ["foreign_policy", "security", "trade"],
    enabled: false,
    sourcePriority: 82,
    credibilityScore: 94,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
    notes:
      "Pausad tills vidare. State.gov Mexico visar relevanta highlights i webbläsare, men serverhämtning får intermittently en Technical Difficulties-sida.",
  },
  {
    id: "us-mexico-travel-advisory",
    name: "US Mexico Travel Advisory",
    country: "USA",
    language: "en",
    type: "website",
    sourceType: "advisory",
    url: "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/mexico-travel-advisory.html",
    trustTier: 1,
    categories: ["security", "society"],
    enabled: true,
    sourcePriority: 84,
    credibilityScore: 92,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "ustr-mexico",
    name: "Office of the US Trade Representative Mexico",
    country: "USA",
    language: "en",
    type: "website",
    sourceType: "government",
    url: "https://ustr.gov/countries-regions/americas/mexico",
    trustTier: 1,
    categories: ["trade", "foreign_policy", "investment_climate"],
    enabled: true,
    sourcePriority: 80,
    credibilityScore: 94,
    defaultDetectedCountry: "Mexiko",
    preserveRawContent: true,
  },
  {
    id: "embajada-suecia-x",
    name: "Embajada de Suecia en Mexico X",
    country: "Sverige",
    language: "es",
    type: "website",
    sourceCategory: "government",
    retrieval: { primary: "social_api" },
    retrievalMethod: "social_api",
    platform: "x",
    sourceType: "social",
    url: "https://x.com/SueciaenMexico",
    trustTier: 1,
    categories: ["sweden_connection", "culture_soft_power", "foreign_policy"],
    enabled: true,
    maxItemsPerRun: 3,
    sourcePriority: 82,
    credibilityScore: 90,
    defaultDetectedCountry: "Mexiko",
  },
  {
    id: "sre-x",
    name: "SRE Mexico X",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceCategory: "government",
    retrieval: { primary: "social_api" },
    retrievalMethod: "social_api",
    platform: "x",
    sourceType: "social",
    url: "https://x.com/SRE_mx",
    trustTier: 1,
    categories: ["foreign_policy", "domestic_politics"],
    enabled: true,
    maxItemsPerRun: 3,
    sourcePriority: 82,
    credibilityScore: 90,
    defaultDetectedCountry: "Mexiko",
  },
  {
    id: "pablo-lemus-x",
    name: "Pablo Lemus X",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceCategory: "government",
    retrieval: { primary: "social_api" },
    retrievalMethod: "social_api",
    platform: "x",
    sourceType: "social",
    url: "https://x.com/PabloLemusN",
    trustTier: 1,
    categories: ["domestic_politics", "society"],
    enabled: true,
    maxItemsPerRun: 3,
    sourcePriority: 78,
    credibilityScore: 88,
    defaultDetectedCountry: "Mexiko",
    defaultDetectedRegion: "Jalisco",
  },
  {
    id: "claudia-sheinbaum-x",
    name: "Claudia Sheinbaum Pardo",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceCategory: "government",
    retrieval: { primary: "social_api" },
    retrievalMethod: "social_api",
    platform: "x",
    sourceType: "social",
    url: "https://x.com/Claudiashein",
    trustTier: 1,
    categories: ["domestic_politics", "foreign_policy"],
    enabled: true,
    maxItemsPerRun: 3,
    sourcePriority: 84,
    credibilityScore: 94,
    defaultDetectedCountry: "Mexiko",
  },
  {
    id: "roberto-velasco-x",
    name: "Roberto Velasco Álvarez",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceCategory: "government",
    retrieval: { primary: "social_api" },
    retrievalMethod: "social_api",
    platform: "x",
    sourceType: "social",
    url: "https://x.com/r_velascoa",
    trustTier: 1,
    categories: ["foreign_policy", "sweden_connection"],
    enabled: true,
    maxItemsPerRun: 3,
    sourcePriority: 80,
    credibilityScore: 92,
    defaultDetectedCountry: "Mexiko",
  },
  {
    id: "marcelo-ebrard-x",
    name: "Marcelo Ebrard C.",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceCategory: "government",
    retrieval: { primary: "social_api" },
    retrievalMethod: "social_api",
    platform: "x",
    sourceType: "social",
    url: "https://x.com/m_ebrard",
    trustTier: 1,
    categories: ["foreign_policy", "trade", "economy"],
    enabled: true,
    maxItemsPerRun: 3,
    sourcePriority: 83,
    credibilityScore: 92,
    defaultDetectedCountry: "Mexiko",
  },
  {
    id: "omar-harfuch-x",
    name: "Omar H Garcia Harfuch",
    country: "Mexiko",
    language: "es",
    type: "website",
    sourceCategory: "government",
    retrieval: { primary: "social_api" },
    retrievalMethod: "social_api",
    platform: "x",
    sourceType: "social",
    url: "https://x.com/OHarfuch",
    trustTier: 1,
    categories: ["security", "domestic_politics"],
    enabled: true,
    maxItemsPerRun: 3,
    sourcePriority: 82,
    credibilityScore: 91,
    defaultDetectedCountry: "Mexiko",
  },
  {
    id: "maria-stenergard-x",
    name: "Maria M Stenergard",
    country: "Sverige",
    language: "sv",
    type: "website",
    sourceCategory: "government",
    retrieval: { primary: "social_api" },
    retrievalMethod: "social_api",
    platform: "x",
    sourceType: "social",
    url: "https://x.com/MariaStenergard",
    trustTier: 1,
    categories: ["foreign_policy", "sweden_connection"],
    enabled: true,
    maxItemsPerRun: 3,
    sourcePriority: 80,
    credibilityScore: 92,
    defaultDetectedCountry: "Sverige",
  },
  {
    id: "ursula-von-der-leyen-x",
    name: "Ursula von der Leyen",
    country: "Internationell",
    language: "en",
    type: "website",
    sourceCategory: "government",
    retrieval: { primary: "social_api" },
    retrievalMethod: "social_api",
    platform: "x",
    sourceType: "social",
    url: "https://x.com/vonderleyen",
    trustTier: 1,
    categories: ["foreign_policy", "trade"],
    enabled: true,
    maxItemsPerRun: 3,
    sourcePriority: 82,
    credibilityScore: 92,
    defaultDetectedCountry: "Internationell",
  },
  {
    id: "kaja-kallas-x",
    name: "Kaja Kallas",
    country: "Internationell",
    language: "en",
    type: "website",
    sourceCategory: "government",
    retrieval: { primary: "social_api" },
    retrievalMethod: "social_api",
    platform: "x",
    sourceType: "social",
    url: "https://x.com/kajakallas",
    trustTier: 1,
    categories: ["foreign_policy", "security"],
    enabled: true,
    maxItemsPerRun: 3,
    sourcePriority: 82,
    credibilityScore: 92,
    defaultDetectedCountry: "Internationell",
  },
];
