import type { EmbassyConfig } from "@/lib/types";

export const swedenMexicoEmbassyConfig: EmbassyConfig = {
  id: "sweden-mexico-city",
  country: "Mexiko",
  countryCode: "MX",
  city: "Mexico City",
  embassyName: "Sveriges ambassad i Mexico City",
  briefingLanguage: "sv",
  relevantLanguages: ["sv", "es", "en"],
  briefingStyle:
    "Kort, strategiskt och diplomatiskt: börja med vad som kräver uppmärksamhet, följt av implikationer för svenska intressen.",
  priorityThemes: [
    "domestic_politics",
    "foreign_policy",
    "economy",
    "trade",
    "security",
    "sweden_connection",
    "investment_climate",
  ],
  swedenRelationPriorities: [
    "svenska företag och investeringar",
    "grön omställning och energi",
    "frihandel och regelbaserad handel",
    "mänskliga rättigheter och rättsstat",
    "innovation, akademi och kulturutbyte",
    "konsulära risker och regional säkerhet",
  ],
  scoringWeights: {
    urgency_score: 1.2,
    diplomatic_relevance_score: 1.4,
    sweden_relevance_score: 1.5,
    economic_impact_score: 1.1,
    security_impact_score: 1.1,
    public_attention_score: 0.7,
  },
  themeCategories: [
    {
      id: "economy",
      label: "Ekonomi",
      description: "Makroekonomi, budget, inflation, finanspolitik.",
    },
    {
      id: "trade",
      label: "Handel",
      description: "Export, import, tullar, handelsflöden och avtal.",
    },
    {
      id: "domestic_politics",
      label: "Inrikespolitik",
      description: "Regering, kongress, partier, lagstiftning.",
    },
    {
      id: "foreign_policy",
      label: "Utrikespolitik",
      description: "Mexikos externa relationer och multilaterala linjer.",
    },
    {
      id: "sweden_connection",
      label: "Sverigekoppling",
      description: "Bilaterala frågor, svenska aktörer och relationer.",
    },
    {
      id: "security",
      label: "Säkerhet",
      description: "Organiserad brottslighet, regional risk, protester.",
    },
    {
      id: "markets",
      label: "Marknader",
      description: "Valuta, räntor, börs och finansiella indikatorer.",
    },
    {
      id: "investment_climate",
      label: "Investeringsklimat",
      description: "Reglering, industri, infrastruktur och företagsrisk.",
    },
    {
      id: "migration",
      label: "Migration",
      description: "Migrationsflöden, gränser och humanitära frågor.",
    },
    {
      id: "society",
      label: "Samhälle",
      description: "Opinion, sociala rörelser, arbetsmarknad.",
    },
    {
      id: "energy",
      label: "Energi",
      description: "Elmarknad, industriell energi, klimat och grön omställning.",
    },
    {
      id: "technology",
      label: "Teknik",
      description: "Digitalisering, cybersäkerhet, innovation.",
    },
    {
      id: "culture_soft_power",
      label: "Kultur och soft power",
      description: "Kultur, utbildning, akademi och offentlig diplomati.",
    },
  ],
  profileModes: [
    {
      id: "daily_overview",
      label: "Dagens lägesbild",
      shortLabel: "Dagens",
      description: "Standardviktning för dagens samlade lägesbild.",
      emphasis: ["prioritet", "förändring", "diplomatisk relevans"],
      categoryWeights: {},
      scoreWeights: {
        urgency_score: 1.3,
        diplomatic_relevance_score: 1.2,
        sweden_relevance_score: 1.1,
      },
    },
    {
      id: "ambassador_briefing",
      label: "Ambassadörsbriefing",
      shortLabel: "Ambassadör",
      description: "Kort beslutsunderlag inför samtal med ambassadören.",
      emphasis: ["risker", "aktörer", "bilateral relevans"],
      categoryWeights: {
        domestic_politics: 1.2,
        foreign_policy: 1.2,
        sweden_connection: 1.3,
      },
      scoreWeights: {
        diplomatic_relevance_score: 1.6,
        sweden_relevance_score: 1.4,
      },
    },
    {
      id: "trade_business",
      label: "Handel och näringsliv",
      shortLabel: "Handel",
      description: "Viktning mot handel, marknad och svenska företag.",
      emphasis: ["investering", "leveranskedjor", "marknadssignaler"],
      categoryWeights: {
        trade: 1.6,
        economy: 1.3,
        markets: 1.3,
        investment_climate: 1.5,
        energy: 1.2,
      },
      scoreWeights: {
        economic_impact_score: 1.6,
        sweden_relevance_score: 1.3,
      },
    },
    {
      id: "political_risk",
      label: "Politisk risk",
      shortLabel: "Politisk risk",
      description: "Fokus på maktbalans, lagstiftning och institutionell risk.",
      emphasis: ["policy", "institutioner", "regulatorisk risk"],
      categoryWeights: {
        domestic_politics: 1.7,
        foreign_policy: 1.2,
        society: 1.1,
      },
      scoreWeights: {
        diplomatic_relevance_score: 1.4,
        public_attention_score: 1.1,
      },
    },
    {
      id: "sweden_connection",
      label: "Sverigekoppling",
      shortLabel: "Sverige",
      description: "Lyfter frågor med direkt eller indirekt svensk betydelse.",
      emphasis: ["bilateralt", "svenska företag", "Sverigebild"],
      categoryWeights: {
        sweden_connection: 2,
        trade: 1.3,
        culture_soft_power: 1.3,
      },
      scoreWeights: {
        sweden_relevance_score: 2,
        diplomatic_relevance_score: 1.2,
      },
    },
    {
      id: "security",
      label: "Säkerhetsfokus",
      shortLabel: "Säkerhet",
      description: "Regional säkerhet, konsulär risk och samhällsstabilitet.",
      emphasis: ["regional risk", "protester", "resiliens"],
      categoryWeights: {
        security: 2,
        migration: 1.3,
        society: 1.2,
      },
      scoreWeights: {
        security_impact_score: 2,
        urgency_score: 1.4,
      },
    },
    {
      id: "weekly_summary",
      label: "Veckosammanfattning",
      shortLabel: "Vecka",
      description: "Viktigaste utvecklingen från föregående vecka.",
      emphasis: ["trend", "förändring", "uppföljning"],
      categoryWeights: {},
      scoreWeights: {
        diplomatic_relevance_score: 1.2,
        public_attention_score: 1.1,
      },
    },
    {
      id: "upcoming_events",
      label: "Kommande händelser",
      shortLabel: "Kommande",
      description: "Kalenderdrivna signaler och förberedelsepunkter.",
      emphasis: ["förberedelse", "mötespunkter", "kalender"],
      categoryWeights: {
        foreign_policy: 1.2,
        trade: 1.2,
        culture_soft_power: 1.1,
      },
      scoreWeights: {
        urgency_score: 1.5,
        diplomatic_relevance_score: 1.3,
      },
    },
  ],
  geography: {
    geographicUnitLabel: "delstat",
    geographicUnitPluralLabel: "delstater",
    nationalLabel: "Nationellt",
    mapLabel: "Regional bevakning",
    priorityDivisionIds: [
      "ciudad-de-mexico",
      "estado-de-mexico",
      "nuevo-leon",
      "jalisco",
      "queretaro",
      "guanajuato",
      "baja-california",
      "chihuahua",
      "puebla",
      "veracruz",
      "yucatan",
      "quintana-roo",
      "sonora",
      "coahuila",
    ],
    regions: [
      {
        id: "north",
        displayName: "Norra Mexiko",
        description: "Gräns, industri, energi, säkerhet och USA-koppling.",
        priority: true,
        divisionIds: [
          "baja-california",
          "baja-california-sur",
          "sonora",
          "chihuahua",
          "coahuila",
          "nuevo-leon",
          "tamaulipas",
          "sinaloa",
          "durango",
        ],
        scoringWeights: {
          economic_impact_score: 1.2,
          security_impact_score: 1.15,
        },
      },
      {
        id: "central",
        displayName: "Centrala Mexiko",
        description: "Federal politik, befolkning, logistik och tjänster.",
        priority: true,
        divisionIds: [
          "ciudad-de-mexico",
          "estado-de-mexico",
          "hidalgo",
          "morelos",
          "puebla",
          "tlaxcala",
        ],
      },
      {
        id: "bajio",
        displayName: "Bajío",
        description: "Industriella kluster, automotive, export och nearshoring.",
        priority: true,
        divisionIds: [
          "aguascalientes",
          "guanajuato",
          "queretaro",
          "san-luis-potosi",
          "zacatecas",
        ],
        scoringWeights: {
          economic_impact_score: 1.3,
          sweden_relevance_score: 1.2,
        },
      },
      {
        id: "west",
        displayName: "Västra Mexiko",
        description: "Teknik, jordbruk, hamnar, innovation och säkerhetsrisk.",
        divisionIds: ["jalisco", "colima", "michoacan", "nayarit"],
      },
      {
        id: "south-southeast",
        displayName: "Syd och sydöst",
        description: "Turism, energi, migration, infrastruktur och miljö.",
        priority: true,
        divisionIds: [
          "veracruz",
          "oaxaca",
          "chiapas",
          "tabasco",
          "campeche",
          "yucatan",
          "quintana-roo",
          "guerrero",
        ],
      },
    ],
    administrativeDivisions: [
      { id: "aguascalientes", displayName: "Aguascalientes", parentRegionId: "bajio", relevanceScore: 56, tags: ["automotive", "export"] },
      { id: "baja-california", displayName: "Baja California", parentRegionId: "north", priority: true, relevanceScore: 78, tags: ["gräns", "industri", "medtech"] },
      { id: "baja-california-sur", displayName: "Baja California Sur", parentRegionId: "north", relevanceScore: 42, tags: ["turism", "miljö"] },
      { id: "campeche", displayName: "Campeche", parentRegionId: "south-southeast", relevanceScore: 45, tags: ["energi", "hamn"] },
      { id: "chiapas", displayName: "Chiapas", parentRegionId: "south-southeast", relevanceScore: 64, tags: ["migration", "social utveckling"] },
      { id: "chihuahua", displayName: "Chihuahua", parentRegionId: "north", priority: true, relevanceScore: 74, tags: ["gräns", "industri", "säkerhet"] },
      { id: "ciudad-de-mexico", displayName: "Ciudad de México", aliases: ["CDMX"], parentRegionId: "central", priority: true, relevanceScore: 96, tags: ["federal politik", "ambassad", "finans"] },
      { id: "coahuila", displayName: "Coahuila", parentRegionId: "north", priority: true, relevanceScore: 70, tags: ["fordon", "stål", "energi"] },
      { id: "colima", displayName: "Colima", parentRegionId: "west", relevanceScore: 55, tags: ["hamn", "logistik"] },
      { id: "durango", displayName: "Durango", parentRegionId: "north", relevanceScore: 48, tags: ["skog", "gruvor"] },
      { id: "estado-de-mexico", displayName: "Estado de México", parentRegionId: "central", priority: true, relevanceScore: 83, tags: ["industri", "logistik", "befolkning"] },
      { id: "guanajuato", displayName: "Guanajuato", parentRegionId: "bajio", priority: true, relevanceScore: 88, scoringWeights: { security_impact_score: 1.3, economic_impact_score: 1.2 }, tags: ["automotive", "säkerhet", "svenska företag"] },
      { id: "guerrero", displayName: "Guerrero", parentRegionId: "south-southeast", relevanceScore: 63, tags: ["säkerhet", "turism"] },
      { id: "hidalgo", displayName: "Hidalgo", parentRegionId: "central", relevanceScore: 52, tags: ["industri", "logistik"] },
      { id: "jalisco", displayName: "Jalisco", parentRegionId: "west", priority: true, relevanceScore: 84, tags: ["teknik", "innovation", "säkerhet"] },
      { id: "michoacan", displayName: "Michoacán", parentRegionId: "west", relevanceScore: 68, tags: ["jordbruk", "säkerhet", "hamn"] },
      { id: "morelos", displayName: "Morelos", parentRegionId: "central", relevanceScore: 49, tags: ["forskning", "turism"] },
      { id: "nayarit", displayName: "Nayarit", parentRegionId: "west", relevanceScore: 41, tags: ["turism", "jordbruk"] },
      { id: "nuevo-leon", displayName: "Nuevo León", parentRegionId: "north", priority: true, relevanceScore: 91, scoringWeights: { economic_impact_score: 1.4, sweden_relevance_score: 1.2 }, tags: ["nearshoring", "industri", "svenska företag"] },
      { id: "oaxaca", displayName: "Oaxaca", parentRegionId: "south-southeast", relevanceScore: 59, tags: ["energi", "social utveckling"] },
      { id: "puebla", displayName: "Puebla", parentRegionId: "central", priority: true, relevanceScore: 72, tags: ["fordon", "industri", "politik"] },
      { id: "queretaro", displayName: "Querétaro", parentRegionId: "bajio", priority: true, relevanceScore: 90, scoringWeights: { sweden_relevance_score: 1.4, economic_impact_score: 1.3 }, tags: ["flyg", "automatisering", "svenska företag"] },
      { id: "quintana-roo", displayName: "Quintana Roo", parentRegionId: "south-southeast", priority: true, relevanceScore: 73, tags: ["turism", "konsulärt", "miljö"] },
      { id: "san-luis-potosi", displayName: "San Luis Potosí", parentRegionId: "bajio", relevanceScore: 69, tags: ["fordon", "logistik"] },
      { id: "sinaloa", displayName: "Sinaloa", parentRegionId: "north", relevanceScore: 66, tags: ["säkerhet", "jordbruk"] },
      { id: "sonora", displayName: "Sonora", parentRegionId: "north", priority: true, relevanceScore: 76, tags: ["energi", "gruvor", "gräns"] },
      { id: "tabasco", displayName: "Tabasco", parentRegionId: "south-southeast", relevanceScore: 58, tags: ["energi", "infrastruktur"] },
      { id: "tamaulipas", displayName: "Tamaulipas", parentRegionId: "north", relevanceScore: 71, tags: ["gräns", "hamn", "säkerhet"] },
      { id: "tlaxcala", displayName: "Tlaxcala", parentRegionId: "central", relevanceScore: 38, tags: ["industri"] },
      { id: "veracruz", displayName: "Veracruz", parentRegionId: "south-southeast", priority: true, relevanceScore: 80, tags: ["hamn", "energi", "migration"] },
      { id: "yucatan", displayName: "Yucatán", parentRegionId: "south-southeast", priority: true, relevanceScore: 69, tags: ["säkerhet", "turism", "logistik"] },
      { id: "zacatecas", displayName: "Zacatecas", parentRegionId: "bajio", relevanceScore: 54, tags: ["gruvor", "säkerhet"] },
    ],
  },
  sources: [
    { id: "el-universal", name: "El Universal", country: "Mexiko", language: "es", type: "rss", url: "https://www.eluniversal.com.mx/arc/outboundfeeds/rss/?outputType=xml", trustTier: 2, categories: ["domestic_politics", "society", "security"], enabled: true },
    { id: "reforma", name: "Reforma", country: "Mexiko", language: "es", type: "website", url: "https://www.reforma.com/", trustTier: 2, categories: ["domestic_politics", "economy", "security"], enabled: true },
    { id: "la-jornada", name: "La Jornada", country: "Mexiko", language: "es", type: "rss", url: "https://www.jornada.com.mx/rss/politica.xml", trustTier: 2, categories: ["domestic_politics", "society"], enabled: true },
    { id: "milenio", name: "Milenio", country: "Mexiko", language: "es", type: "rss", url: "https://www.milenio.com/", trustTier: 2, categories: ["domestic_politics", "security", "society"], enabled: true },
    { id: "el-financiero", name: "El Financiero", country: "Mexiko", language: "es", type: "rss", url: "https://www.elfinanciero.com.mx/arc/outboundfeeds/rss/?outputType=xml", trustTier: 2, categories: ["economy", "markets", "trade"], enabled: true },
    { id: "expansion", name: "Expansión", country: "Mexiko", language: "es", type: "rss", url: "https://expansion.mx/rss", trustTier: 2, categories: ["economy", "investment_climate", "technology"], enabled: true },
    { id: "gobierno-mexico", name: "Gobierno de México", country: "Mexiko", language: "es", type: "website", url: "https://www.gob.mx/", trustTier: 1, categories: ["domestic_politics", "foreign_policy"], enabled: true },
    { id: "sre", name: "Secretaría de Relaciones Exteriores", country: "Mexiko", language: "es", type: "website", url: "https://www.gob.mx/sre", trustTier: 1, categories: ["foreign_policy", "sweden_connection"], enabled: true },
    { id: "banxico", name: "Banco de México", country: "Mexiko", language: "es", type: "api", url: "https://www.banxico.org.mx/", trustTier: 1, categories: ["economy", "markets"], enabled: true },
    { id: "inegi", name: "INEGI", country: "Mexiko", language: "es", type: "api", url: "https://www.inegi.org.mx/", trustTier: 1, categories: ["economy", "society"], enabled: true },
    { id: "regeringen", name: "Regeringen.se", country: "Sverige", language: "sv", type: "rss", url: "https://www.regeringen.se/", trustTier: 1, categories: ["foreign_policy", "sweden_connection"], enabled: true },
    { id: "ud", name: "Utrikesdepartementet", country: "Sverige", language: "sv", type: "website", url: "https://www.regeringen.se/sveriges-regering/utrikesdepartementet/", trustTier: 1, categories: ["foreign_policy", "sweden_connection"], enabled: true },
    { id: "business-sweden", name: "Business Sweden", country: "Sverige", language: "sv", type: "website", url: "https://www.business-sweden.com/", trustTier: 1, categories: ["trade", "investment_climate", "sweden_connection"], enabled: true },
    { id: "kommerskollegium", name: "Kommerskollegium", country: "Sverige", language: "sv", type: "website", url: "https://www.kommerskollegium.se/", trustTier: 1, categories: ["trade", "foreign_policy"], enabled: true },
    { id: "scb", name: "SCB", country: "Sverige", language: "sv", type: "api", url: "https://www.scb.se/", trustTier: 1, categories: ["economy"], enabled: true },
    { id: "riksbanken", name: "Riksbanken", country: "Sverige", language: "sv", type: "api", url: "https://www.riksbank.se/", trustTier: 1, categories: ["economy", "markets"], enabled: true },
    { id: "embassy-mexico", name: "Swedish Embassy Mexico", country: "Mexiko", language: "sv", type: "website", url: "https://www.swedenabroad.se/sv/utlandsmyndigheter/mexiko-mexico-city/", trustTier: 1, categories: ["sweden_connection", "culture_soft_power"], enabled: true },
    { id: "reuters", name: "Reuters", country: "Internationell", language: "en", type: "rss", url: "https://www.reuters.com/", trustTier: 1, categories: ["economy", "foreign_policy", "markets", "security"], enabled: true },
    { id: "ap", name: "AP", country: "Internationell", language: "en", type: "rss", url: "https://apnews.com/", trustTier: 1, categories: ["domestic_politics", "society", "security"], enabled: true },
    { id: "bbc", name: "BBC", country: "Storbritannien", language: "en", type: "rss", url: "https://feeds.bbci.co.uk/news/world/latin_america/rss.xml", trustTier: 2, categories: ["foreign_policy", "security", "society"], enabled: true },
    { id: "ft", name: "Financial Times", country: "Storbritannien", language: "en", type: "website", url: "https://www.ft.com/", trustTier: 1, categories: ["economy", "markets", "investment_climate"], enabled: true },
    { id: "economist", name: "The Economist", country: "Storbritannien", language: "en", type: "website", url: "https://www.economist.com/", trustTier: 2, categories: ["economy", "foreign_policy", "society"], enabled: true },
    { id: "imf", name: "IMF", country: "Internationell", language: "en", type: "api", url: "https://www.imf.org/", trustTier: 1, categories: ["economy", "markets"], enabled: true },
    { id: "oecd", name: "OECD", country: "Internationell", language: "en", type: "api", url: "https://www.oecd.org/", trustTier: 1, categories: ["economy", "trade", "society"], enabled: true },
    { id: "world-bank", name: "World Bank", country: "Internationell", language: "en", type: "api", url: "https://www.worldbank.org/", trustTier: 1, categories: ["economy", "investment_climate", "society"], enabled: true },
  ],
};
